/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as InstallRouteImport } from './routes/install'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIdRouteImport } from './routes/tv.$id'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as WatchKindIdRouteImport } from './routes/watch.$kind.$id'
import { Route as AuthenticatedLibraryHistoryRouteImport } from './routes/_authenticated/library.history'
import { Route as AuthenticatedLibraryFavoritesRouteImport } from './routes/_authenticated/library.favorites'
import { Route as AuthenticatedLibraryContinueRouteImport } from './routes/_authenticated/library.continue'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as TvIdSeasonSeasonEpisodeEpisodeRouteImport } from './routes/tv.$id.season.$season.episode.$episode'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const WatchKindIdRoute = WatchKindIdRouteImport.update({
  id: '/watch/$kind/$id',
  path: '/watch/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryHistoryRoute =
  AuthenticatedLibraryHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryFavoritesRoute =
  AuthenticatedLibraryFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryContinueRoute =
  AuthenticatedLibraryContinueRouteImport.update({
    id: '/continue',
    path: '/continue',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdSeasonSeasonEpisodeEpisodeRoute =
  TvIdSeasonSeasonEpisodeEpisodeRouteImport.update({
    id: '/season/$season/episode/$episode',
    path: '/season/$season/episode/$episode',
    getParentRoute: () => TvIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/install': typeof InstallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/movie/$id': typeof MovieIdRoute
  '/tv/$id': typeof TvIdRouteWithChildren
  '/library/continue': typeof AuthenticatedLibraryContinueRoute
  '/library/favorites': typeof AuthenticatedLibraryFavoritesRoute
  '/library/history': typeof AuthenticatedLibraryHistoryRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/tv/$id/season/$season/episode/$episode': typeof TvIdSeasonSeasonEpisodeEpisodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/install': typeof InstallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/movie/$id': typeof MovieIdRoute
  '/tv/$id': typeof TvIdRouteWithChildren
  '/library/continue': typeof AuthenticatedLibraryContinueRoute
  '/library/favorites': typeof AuthenticatedLibraryFavoritesRoute
  '/library/history': typeof AuthenticatedLibraryHistoryRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/tv/$id/season/$season/episode/$episode': typeof TvIdSeasonSeasonEpisodeEpisodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/install': typeof InstallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/movie/$id': typeof MovieIdRoute
  '/tv/$id': typeof TvIdRouteWithChildren
  '/_authenticated/library/continue': typeof AuthenticatedLibraryContinueRoute
  '/_authenticated/library/favorites': typeof AuthenticatedLibraryFavoritesRoute
  '/_authenticated/library/history': typeof AuthenticatedLibraryHistoryRoute
  '/watch/$kind/$id': typeof WatchKindIdRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/tv/$id/season/$season/episode/$episode': typeof TvIdSeasonSeasonEpisodeEpisodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/home'
    | '/install'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/admin'
    | '/billing'
    | '/library'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/movie/$id'
    | '/tv/$id'
    | '/library/continue'
    | '/library/favorites'
    | '/library/history'
    | '/watch/$kind/$id'
    | '/api/public/stripe/webhook'
    | '/tv/$id/season/$season/episode/$episode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/home'
    | '/install'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/admin'
    | '/billing'
    | '/library'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/movie/$id'
    | '/tv/$id'
    | '/library/continue'
    | '/library/favorites'
    | '/library/history'
    | '/watch/$kind/$id'
    | '/api/public/stripe/webhook'
    | '/tv/$id/season/$season/episode/$episode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/discover'
    | '/home'
    | '/install'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/library'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/movie/$id'
    | '/tv/$id'
    | '/_authenticated/library/continue'
    | '/_authenticated/library/favorites'
    | '/_authenticated/library/history'
    | '/watch/$kind/$id'
    | '/api/public/stripe/webhook'
    | '/tv/$id/season/$season/episode/$episode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  HomeRoute: typeof HomeRoute
  InstallRoute: typeof InstallRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MovieIdRoute: typeof MovieIdRoute
  TvIdRoute: typeof TvIdRouteWithChildren
  WatchKindIdRoute: typeof WatchKindIdRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/watch/$kind/$id': {
      id: '/watch/$kind/$id'
      path: '/watch/$kind/$id'
      fullPath: '/watch/$kind/$id'
      preLoaderRoute: typeof WatchKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library/history': {
      id: '/_authenticated/library/history'
      path: '/history'
      fullPath: '/library/history'
      preLoaderRoute: typeof AuthenticatedLibraryHistoryRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/favorites': {
      id: '/_authenticated/library/favorites'
      path: '/favorites'
      fullPath: '/library/favorites'
      preLoaderRoute: typeof AuthenticatedLibraryFavoritesRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/continue': {
      id: '/_authenticated/library/continue'
      path: '/continue'
      fullPath: '/library/continue'
      preLoaderRoute: typeof AuthenticatedLibraryContinueRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id/season/$season/episode/$episode': {
      id: '/tv/$id/season/$season/episode/$episode'
      path: '/season/$season/episode/$episode'
      fullPath: '/tv/$id/season/$season/episode/$episode'
      preLoaderRoute: typeof TvIdSeasonSeasonEpisodeEpisodeRouteImport
      parentRoute: typeof TvIdRoute
    }
  }
}

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryContinueRoute: typeof AuthenticatedLibraryContinueRoute
  AuthenticatedLibraryFavoritesRoute: typeof AuthenticatedLibraryFavoritesRoute
  AuthenticatedLibraryHistoryRoute: typeof AuthenticatedLibraryHistoryRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryContinueRoute: AuthenticatedLibraryContinueRoute,
  AuthenticatedLibraryFavoritesRoute: AuthenticatedLibraryFavoritesRoute,
  AuthenticatedLibraryHistoryRoute: AuthenticatedLibraryHistoryRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TvIdRouteChildren {
  TvIdSeasonSeasonEpisodeEpisodeRoute: typeof TvIdSeasonSeasonEpisodeEpisodeRoute
}

const TvIdRouteChildren: TvIdRouteChildren = {
  TvIdSeasonSeasonEpisodeEpisodeRoute: TvIdSeasonSeasonEpisodeEpisodeRoute,
}

const TvIdRouteWithChildren = TvIdRoute._addFileChildren(TvIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  HomeRoute: HomeRoute,
  InstallRoute: InstallRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MovieIdRoute: MovieIdRoute,
  TvIdRoute: TvIdRouteWithChildren,
  WatchKindIdRoute: WatchKindIdRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
